mozilla-services/amo-blocklist-ui

- components/AddonForm.jsx
- components/CertificateForm.jsx
- components/GenericForm.jsx
- components/GfxForm.jsx
- components/PluginForm.jsx
- components/styles.css
- fixtures/AddonForm/default.js
- fixtures/CertificateForm/default.js
- fixtures/GfxForm/default.js
- fixtures/GfxForm/invalid.js
- fixtures/PluginForm/default.js
- fixtures/PluginForm/loaded.js
- package.json
- schema/addon.js
- schema/certificate.js
- schema/gfx.js
- schema/plugin.js
- schema/versionRange.js
> Form validation, json schema defaults support.

- .travis.yml
- README.md
- package.json
[![Build Status](https://travis-ci.org/mozilla-services/amo-blocklist-ui.svg)](https://travis-ci.org/mozilla-services/amo-blocklist-ui)
> Added travis build configuration.

- scripts/components/CollectionList.js
- scripts/containers/CollectionListPage.js
> Closes #8: Edit on double-click.

- css/styles.css
- scripts/actions/collection.js
- scripts/actions/collections.js
- scripts/components/AddForm.js
- scripts/components/EditForm.js
- scripts/components/Sidebar.js
- scripts/reducers/collections.js
- test/actions/collection_test.js
- test/reducers/collections_test.js
> Closes #10: Visual indicator for unsynced collections.

- .eslintrc
- css/styles.css
- package.json
- scripts/actions/collection.js
- scripts/actions/notifications.js
- scripts/components/Notifications.js
- test/actions/collection_test.js
> Handle synchronization results.

- package.json
- scripts/actions/collection.js
> Move dev dependencies to app dependencies

- .travis.yml
- package.json
- scripts/actions/collection.js
- scripts/components/CollectionList.js
- scripts/components/GenericForm.js
- scripts/components/Notifications.js
- scripts/index.js
- scripts/reducers/collection.js
- test/actions/collection_test.js
- test/containers/AddForm_test.js
- test/containers/CollectionList_test.js
- test/containers/EditFormPage_test.js
- test/containers/Notifications_test.js
- test/containers/SettingsPage_test.js
- test/containers/Sidebar_test.js
- test/reducers/collection_test.js
- test/test-utils.js
This is now ready for review. r=? @leplatrem
> Container tests.

- css/styles.css
- devServer.js
- scripts/actions/collection.js
- scripts/actions/settings.js
- scripts/components/BusyIndicator.js
- scripts/components/CollectionList.js
- scripts/containers/CollectionListPage.js
- test/actions/collection_test.js
- test/actions/settings_test.js
- test/components/BusyIndicator_test.js
- test/containers/CollectionList_test.js
This addresses an issue with settings updates which are not properly taken into account.
> Ensure Kinto parameters are properly validated.

- css/styles.css
- scripts/actions/serverInfo.js
- scripts/components/Settings.js
- scripts/containers/SettingsPage.js
- scripts/reducers/index.js
- scripts/reducers/serverInfo.js
- test/actions/serverInfo_test.js
- test/actions/settings_test.js
- test/containers/SettingsPage_test.js
- test/reducers/serverInfo_test.js
r=? @leplatrem
The branch is live on gh-pages to ease testing.
> Added server settings live HTTP checks.

- amo-blocklist.json
> Use 'add-on' instead of 'addon'

- amo-blocklist.json
> Open the Versions section by default for add-ons and plugins, and display it above prefs

- amo-blocklist.json
> The 'feature' field is optional for GFX forms

- amo-blocklist.json
> Add a 'driverVersionMax' field for GFX forms

- amo-blocklist.json
> Added the missing 'os' field to both add-on and plugin forms

- amo-blocklist.json
> We can have 0..n TargetApplications for add-ons and plugins

- amo-blocklist.json
> The target application id field is a dropdown

- amo-blocklist.json
> Add missing feature status (fixes #66)

- amo-blocklist.json
> Switch Gfx OS to enum (fixes #67)

- amo-blocklist.json
- package.json
> Add meaningful labels for target applications

- amo-blocklist.json
> Add meaningful labels for the vulnerabilityStatus fields (pair=@natim)

- amo-blocklist.json
> Add missing fields for Gfx (fixes #62)

- amo-blocklist.json
> Add field with date of creation

- amo-blocklist.json
> Add xpcom ABI field (fixes #84)

- amo-blocklist.json
> Add regex check for comma-separated (fixes #85)

- amo-blocklist.json
* Due to Kinto/kinto#549
Note: I tried quickly and it seems to behave properly with record creation.
But fails with update:
r? @n1k0, @Natim
> Add hidden field for record id in schema

- amo-blocklist.json
> The collection name is addons.

- amo-blocklist.json
- package.json
kinto-admin v0.13.1 release notes: https://github.com/Kinto/kinto-admin/releases/tag/v0.13.1
r=? @leplatrem 
Note: dunno why the diff of the json config file is that ugly; basically it's just adding a `collections` level at the root of the tree...
> Upgraded kinto-admin to v0.13.1.

- amo-blocklist.json
r? @n1k0 
f? @leplatrem @glasserc
> Update the label following Kinto/kinto-admin#47 PR.

- amo-blocklist.json
Adding schema in jsonschema to make kinto-admin works when schema validation is enabled on server side.
r=@n1k0
> Add the schema version in the JSONSchema.

- amo-blocklist.json
- package.json
> Set blockID should be readonly. Fixes #91

- package.json
> Upgrade to kinto-admin@0.15.0

- amo-blocklist.json
> ``details.created`` should be readonly. Fixes #79

- amo-blocklist.json
> Add versionRange to Gfx entries

- .travis.yml
> Add a travis.yml configuration file.

- amo-blocklist.json
> Remove xpcomabi field for plugins.

- amo-blocklist.json
> Add GFX ui:order

- amo-blocklist.json
> Order details fields

- amo-blocklist.json
> Remove vulnerabilityStatus for addons.

- amo-blocklist.json
> Update severity enum possible values.

- amo-blocklist.json
> Define missing ui:order

- amo-blocklist.json
WiP addressing @jvillalobos feedback.
> Prepare new release
